{
    parserClass="com.vgfplugin.parser.SimpleParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="Vgf"
    psiImplClassSuffix="Impl"
    psiPackage="com.vgfplugin.psi"
    psiImplPackage="com.vgfplugin.psi.impl"

    elementTypeHolderClass="com.vgfplugin.psi.VgfTypes"
    elementTypeClass="com.vgfplugin.psi.VgfElementType"
    tokenTypeClass="com.vgfplugin.psi.VgfTokenType"
}

vgfFile         ::= item_*

private item_   ::= ( definition | COMMENT | LINE_TERMINATOR )

definition      ::= RULE_NAME production+
production      ::= PRODUCTION_NAME ( LITERAL | special_token | property )+
                  | RULE_NAME
special_token   ::= INDENT
                  | DEDENT
                  | ENDMARKER
                  | NEWLINE
                  | PERIOD
                  | EQUALS
                  | COMMA
                  | OPEN_PAREN
                  | CLOSE_PAREN
                  | COLON
                  | L_ARROW
                  | R_ARROW
                  | ELLIPSIS
                  | INT
                  | FLOAT
                  | STRING
                  | NAME
                  | UNDERSCORE
                  | CLASS
                  | OPERATOR
property        ::= PROPERTY_NAME ( RULE_NAME | special_token ) modifier?
modifier        ::= OPTIONAL
                  | REPEAT
                  | MIN_REPEAT
                  | SEP_REPEAT SEP_LIT
                  | MIN_SEP_REPEAT SEP_LIT
